---
name: str()
model: str(required=False)
rest_endpoint: str(required=False)
get_rest_endpoint: str(required=False)
post_rest_endpoint: str(required=False)
type: str(required=False)
minimum_version: str(required=False)
ds_description: str(required=False)
res_description: str(required=False)
doc_category: str(required=False)
exclude_test: bool(required=False)
root_element: str(required=False)
has_version: bool(required=False)
id_attribute: str(required=False)
id_from_query_path: str(required=False) # Specify path to ID container if ID is not included in POST response and needs to be resolved via separate GET request
id_from_query_path_attribute: str(required=False) # Specify attribute name of ID, only relevant if "id_from_query_path" option used, default is "id"
skip_templates: list(str(), required=False)
attributes: list(include('attribute'), required=False)
test_prerequisites: str(required=False)
remove_id: bool(required=False)
---
attribute:
  model_name: str(required=False)
  response_model_name: str(required=False)
  tf_name: str(required=False)
  type: enum('String', 'Int64', 'Bool', 'List', 'Set', 'Version', 'Versions', 'StringList', 'Int64List', required=False)
  object_type: enum('object', 'tree', 'list', required=False)
  model_type_string: bool(required=False)
  bool_empty_string: bool(required=False)
  data_path: list(str(), required=False)
  keys: list(str(), required=False)
  id: bool(required=False)
  reference: bool(required=False) # Indicates that the attribute is being used in the url path
  variable: bool(required=False)
  mandatory: bool(required=False)
  parcel_mandatory: bool(required=False) # Set to true if profile parcel attribute requires either a "global" or "variable" value
  write_only: bool(required=False)
  tf_only: bool(required=False)
  exclude_test: bool(required=False)
  exclude_example: bool(required=False)
  exclude_ignore: bool(required=False) # If true the object will not be included in the payload if vipType="ignore"
  node_only_container: bool(required=False) # Some node-only attributes are at the same time a container for other attributes, in this case set to "true"
  description: str(required=False)
  example: any(str(), int(), bool(), required=False)
  enum_values: list(str(), required=False)
  ignore_enum: bool(required=False)
  min_list: int(required=False)
  max_list: int(required=False)
  min_int: int(required=False)
  max_int: int(required=False)
  min_float: num(required=False)
  max_float: num(required=False)
  string_patterns: list(str(), required=False)
  string_min_length: int(required=False)
  string_max_length: int(required=False)
  default_value: any(str(), int(), bool(), required=False)
  default_value_present: bool(required=False)
  value: any(str(), int(), bool(), required=False)
  test_value: str(required=False)
  always_include: bool(required=False)
  attributes: list(include('attribute'), required=False)
  conditional_attribute: include('conditional_attribute', required=False)
  query_param: bool(required=False)
  no_augment_config: bool(required=False) # If true do not augment with model data

conditional_attribute:
  name: str()
  value: str()
