---
name: str()
model: str(required=False)
type: str(required=False)
minimum_version: str()
ds_description: str(required=False)
res_description: str(required=False)
doc_category: str(required=False)
exclude_test: bool(required=False)
root_element: str(required=False)
skip_templates: list(str(), required=False)
attributes: list(include('attribute'), required=False)
---
attribute:
  model_name: str()
  tf_name: str(required=False)
  type: enum('String', 'Int64', 'Bool', 'List', required=False)
  object_type: enum('object', 'tree', 'list', required=False)
  model_type_string: bool(required=False)
  data_path: list(str(), required=False)
  keys: list(str(), required=False)
  id: bool(required=False)
  variable: bool(required=False)
  mandatory: bool(required=False)
  write_only: bool(required=False)
  tf_only: bool(required=False)
  exclude_test: bool(required=False)
  exclude_example: bool(required=False)
  exclude_ignore: bool(required=False)
  description: str(required=False)
  example: any(str(), int(), bool(), required=False)
  enum_values: list(str(), required=False)
  min_list: int(required=False)
  max_list: int(required=False)
  min_int: int(required=False)
  max_int: int(required=False)
  min_float: num(required=False)
  max_float: num(required=False)
  string_patterns: list(str(), required=False)
  string_min_length: int(required=False)
  string_max_length: int(required=False)
  default_value: any(str(), int(), bool(), required=False)
  value: any(str(), int(), bool(), required=False)
  attributes: list(include('attribute'), required=False)
