resource "sdwan_system_omp_profile_parcel" "example" {
  name                        = "Example"
  description                 = "My Example"
  feature_profile_id          = "f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac"
  graceful_restart            = true
  overlay_as                  = 10
  paths_advertised_per_prefix = 4
  ecmp_limit                  = 4
  shutdown                    = false
  omp_admin_distance_ipv4     = 10
  omp_admin_distance_ipv6     = 20
  advertisement_interval      = 1
  graceful_restart_timer      = 43200
  eor_timer                   = 300
  holdtime                    = 60
  advertise_ipv4_bgp          = false
  advertise_ipv4_ospf         = false
  advertise_ipv4_ospf_v3      = false
  advertise_ipv4_connected    = false
  advertise_ipv4_static       = false
  advertise_ipv4_eigrp        = false
  advertise_ipv4_lisp         = false
  advertise_ipv4_isis         = false
  advertise_ipv6_bgp          = true
  advertise_ipv6_ospf         = true
  advertise_ipv6_connected    = true
  advertise_ipv6_static       = true
  advertise_ipv6_eigrp        = true
  advertise_ipv6_lisp         = true
  advertise_ipv6_isis         = true
  ignore_region_path_length   = false
  transport_gateway           = "prefer"
  site_types                  = ["type-1"]
}
