---
name: Application Priority QoS
rest_endpoint: /v1/feature-profile/sdwan/application-priority/%v/qos-policy
minimum_version: 20.12.0
id_attribute: id
test_tags: [SDWAN_2012]
parcel_type: policy
attributes:
  - tf_name: feature_profile_id
    reference: true
    type: String
    mandatory: true
    description: Feature Profile ID
    example: f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac
    test_value: sdwan_application_priority_feature_profile.test.id
  - model_name: interfaces
    tf_name: target_interface
    data_path: [target]
    example: '{{interface_var_1}}'
  - model_name: qosSchedulers
    data_path: [qosMap]
    attributes:
      - model_name: refId
        tf_name: forwarding_class_id
        data_path: [classMapRef]
        exclude_test: true
        example: a509839f-33aa-492a-ab8e-6a6fe70d7d79
      - model_name: drops 
        example: tail-drop
      - model_name: queue
        id: true
        example: 0
      - model_name: bandwidthPercent
        tf_name: bandwidth
        example: 10
      - model_name: scheduling
        tf_name: scheduling_type
        example: llq

test_prerequisites: |
  resource "sdwan_application_priority_feature_profile" "test" {
    name        = "TF_TEST"
    description = "Terraform test"
  }