---
name: System Security
rest_endpoint: /v1/feature-profile/sdwan/system/%v/security
minimum_version: 20.12.0
test_tags: [SDWAN_2012]
attributes:
  - tf_name: feature_profile_id
    reference: true
    type: String
    description: Feature Profile ID
    example: f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac
    test_value: sdwan_system_feature_profile.test.id
  - model_name: rekey
    example: 86400
  - model_name: replayWindow
    tf_name: anti_replay_window
    example: 512
  - model_name: extendedArWindow
    tf_name: extended_anti_replay_window
    example: 256
  - model_name: pairwiseKeying
    tf_name: ipsec_pairwise_keying
    example: false
  - model_name: integrityType
    example: esp
  - model_name: keychain
    tf_name: keychains
    attributes:
      - model_name: name
        tf_name: key_chain_name
        example: aaa
      - model_name: id
        id: true
        tf_name: key_id
        example: 1
  - model_name: key
    tf_name: keys
    attributes:
      - model_name: id
        id: true
        example: 0
      - model_name: name
        example: aaa
      - model_name: sendId
        example: 1
      - model_name: recvId
        tf_name: receiver_id
        example: 2
      - model_name: includeTcpOptions
        example: false
      - model_name: acceptAoMismatch
        example: false
      - model_name: tcp
        tf_name: crypto_algorithm
        example: aes-128-cmac
      - model_name: keyString
        write_only: true
        example: abcabc
      - model_name: local
        tf_name: send_life_time_local
        data_path: [sendLifetime]
        example: true
      - model_name: startEpoch
        tf_name: send_life_time_start_epoch
        data_path: [sendLifetime]
        example: 1659284400
      - model_name: infinite
        tf_name: send_life_time_infinite
        data_path: [sendLifetime, oneOfendChoice]
        example: true
      - model_name: duration
        tf_name: send_life_time_duration
        data_path: [sendLifetime, oneOfendChoice]
        exclude_test: true
        example: 100
      - model_name: exact
        tf_name: send_life_time_exact
        data_path: [sendLifetime, oneOfendChoice]
        exclude_test: true
        example: 1659284400
      - model_name: local
        tf_name: accept_life_time_local
        data_path: [acceptLifetime]
        example: true
      - model_name: startEpoch
        tf_name: accept_life_time_start_epoch
        data_path: [acceptLifetime]
        example: 1659284400
      - model_name: infinite
        tf_name: accept_life_time_infinite
        data_path: [acceptLifetime, oneOfendChoice]
        example: true
      - model_name: duration
        tf_name: accept_life_time_duration
        data_path: [acceptLifetime, oneOfendChoice]
        exclude_test: true
        example: 100
      - model_name: exact
        tf_name: accept_life_time_exact
        data_path: [acceptLifetime, oneOfendChoice]
        exclude_test: true
        example: 1659284400

test_prerequisites: |
  resource "sdwan_system_feature_profile" "test" {
    name = "TF_TEST"
    description = "Terraform test"
  }