---
name: CLI Config Profile Parcel
rest_endpoint: /v1/feature-profile/sdwan/cli/%v/config/
minimum_version: 20.12.0
id_attribute: parcelId
test_tags: [SDWAN_2012]
doc_category: Profile Parcels
attributes:
  - tf_name: feature_profile_id
    reference: true
    type: String
    mandatory: true
    description: Feature Profile ID
    example: f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac
    test_value: sdwan_cli_feature_profile.test.id
  - model_name: name
    type: String
    mandatory: true
    description: The name of the profile parcel
    example: Example
  - model_name: description
    type: String
    mandatory: true
    description: The description of the profile parcel
    example: My Example
  - model_name: config
    tf_name: cli_config
    data_path: [data]
    type: String
    mandatory: true
    description: CLI configuration
    example: '! Enable new BGP community format\nip bgp-community new-format\n'

test_prerequisites: |
  resource "sdwan_cli_feature_profile" "test" {
    name        = "TF_TEST"
    description = "Terraform test"
  }