---
name: Configuration Group Deploy
rest_endpoint: /v1/config-group/%v/device/deploy/
no_data_source: true
no_import: true
remove_id: true
minimum_version: 20.12.0
test_tags: [CONFIG_GROUP_DEPLOY]
doc_category: Configuration Group
attributes:
  - tf_name: configuration_group_id
    reference: true
    type: String
    mandatory: true
    description: Configuration Group ID
    example: f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac
    test_value: sdwan_configuration_group_device_variables.test.configuration_group_id
  - model_name: devices
    type: List
    mandatory: true
    description: List of devices
    attributes:
      - model_name: id
        type: String
        id: true
        description: Device ID
        example: C8K-15411CCC-D476-0B3B-21F2-5D6AC387EE7B

test_prerequisites: |
  resource "sdwan_system_feature_profile" "test" {
    name        = "SYSTEM_TF"
    description = "My system feature profile 1"
  }

  resource "sdwan_configuration_group" "test" {
    name        = "TF_TEST"
    description = "Terraform test"
    solution    = "sdwan"
    feature_profiles = [
      {
        id = sdwan_system_feature_profile.test.id
      }
    ]
  }

  resource "sdwan_configuration_group_devices" "test" {
    configuration_group_id = sdwan_configuration_group.test.id
    devices = [{
      id = "C8K-15411CCC-D476-0B3B-21F2-5D6AC387EE7B"
    }]
  }

  resource "sdwan_configuration_group_device_variables" "test" {
    configuration_group_id = sdwan_configuration_group_devices.test.configuration_group_id
    solution = "sdwan"
    devices = [{
      device_id = "C8K-15411CCC-D476-0B3B-21F2-5D6AC387EE7B"
      variables = [
        {
          name  = "host_name"
          value = "edge1"
        },
        {
          name  = "pseudo_commit_timer"
          value = "0"
        },
        {
          name  = "site_id"
          value = "1"
        },
        {
          name  = "system_ip"
          value = "10.1.1.1"
        },
      ]
    }]
  }