---
name: Configuration Group Device Variables
rest_endpoint: /v1/config-group/%v/device/variables/
remove_id: true
no_import: true
minimum_version: 20.12.0
test_tags: [SDWAN_2012]
doc_category: Configuration Group
attributes:
  - tf_name: configuration_group_id
    reference: true
    type: String
    mandatory: true
    description: Configuration Group ID
    example: f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac
    test_value: sdwan_configuration_group.test.id
  - model_name: solution
    response_model_name: family
    type: String
    mandatory: true
    enum_values: [mobility, sdwan, nfvirtual]
    description: Type of solution
    example: sdwan
  - model_name: devices
    type: List
    mandatory: true
    description: List of devices
    attributes:
      - model_name: device-id
        type: String
        id: true
        description: Device ID
        example: C8K-15411CCC-D476-0B3B-21F2-5D6AC387EE7B
        test_value: sdwan_configuration_group_devices.test.devices.0.id
      - model_name: variables
        type: List
        description: List of variables
        attributes:
          - model_name: name
            type: String
            id: true
            description: Variable name
            example: host_name
          - model_name: value
            type: String
            mandatory: true
            description: Variable value
            example: edge1
  - model_name: groups
    type: List
    description: List of device groups
    exclude_test: true
    attributes:
      - model_name: name
        type: String
        id: true
        description: Group name
        example: name1
      - model_name: group-variables
        tf_name: variables
        type: List
        description: List of variables
        attributes:
          - model_name: name
            type: String
            id: true
            description: Variable name
            example: var
          - model_name: value
            type: String
            mandatory: true
            description: Variable value
            example: value1

test_prerequisites: |
  resource "sdwan_system_feature_profile" "test" {
    name        = "SYSTEM_TF"
    description = "My system feature profile 1"
  }

  resource "sdwan_configuration_group" "test" {
    name        = "TF_TEST"
    description = "Terraform test"
    solution    = "sdwan"
    feature_profiles = [
      {
        id = sdwan_system_feature_profile.test.id
      }
    ]
  }

  resource "sdwan_configuration_group_devices" "test" {
    configuration_group_id = sdwan_configuration_group.test.id
    devices = [{
      id = "C8K-15411CCC-D476-0B3B-21F2-5D6AC387EE7B"
    }]
  }