---
name: Configuration Group Devices
rest_endpoint: /v1/config-group/%v/device/associate/
remove_id: true
minimum_version: 20.12.0
test_tags: [SDWAN_2012]
doc_category: Configuration Group
attributes:
  - tf_name: configuration_group_id
    reference: true
    type: String
    mandatory: true
    description: Configuration Group ID
    example: f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac
    test_value: sdwan_configuration_group.test.id
  - model_name: devices
    type: List
    mandatory: true
    description: List of devices
    attributes:
      - model_name: id
        type: String
        id: true
        description: Device ID
        example: C8K-15411CCC-D476-0B3B-21F2-5D6AC387EE7B

test_prerequisites: |
  resource "sdwan_configuration_group" "test" {
    name        = "TF_TEST"
    description = "Terraform test"
    solution    = "sdwan"
  }