// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceSdwanIPv4PrefixListPolicyObject(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.sdwan_ipv4_prefix_list_policy_object.test", "name", "Example"))
	checks = append(checks, resource.TestCheckResourceAttr("data.sdwan_ipv4_prefix_list_policy_object.test", "entries.0.prefix", "10.0.0.0/12"))
	checks = append(checks, resource.TestCheckResourceAttr("data.sdwan_ipv4_prefix_list_policy_object.test", "entries.0.le", "32"))
	checks = append(checks, resource.TestCheckResourceAttr("data.sdwan_ipv4_prefix_list_policy_object.test", "entries.0.ge", "24"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanIPv4PrefixListPolicyObjectConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

func testAccDataSourceSdwanIPv4PrefixListPolicyObjectConfig() string {
	config := ""
	config += `resource "sdwan_ipv4_prefix_list_policy_object" "test" {` + "\n"
	config += `	name = "Example"` + "\n"
	config += `	entries = [{` + "\n"
	config += `	  prefix = "10.0.0.0/12"` + "\n"
	config += `	  le = 32` + "\n"
	config += `	  ge = 24` + "\n"
	config += `	}]` + "\n"
	config += `}` + "\n"

	config += `
		data "sdwan_ipv4_prefix_list_policy_object" "test" {
			id = sdwan_ipv4_prefix_list_policy_object.test.id
		}
	`
	return config
}
