// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceSdwanSystemBFDProfileParcel(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanSystemBFDProfileParcelConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_system_bfd_profile_parcel.test", "multiplier", "3"),
					resource.TestCheckResourceAttr("data.sdwan_system_bfd_profile_parcel.test", "poll_interval", "100"),
					resource.TestCheckResourceAttr("data.sdwan_system_bfd_profile_parcel.test", "default_dscp", "8"),
					resource.TestCheckResourceAttr("data.sdwan_system_bfd_profile_parcel.test", "colors.0.color", "3g"),
					resource.TestCheckResourceAttr("data.sdwan_system_bfd_profile_parcel.test", "colors.0.hello_interval", "200"),
					resource.TestCheckResourceAttr("data.sdwan_system_bfd_profile_parcel.test", "colors.0.multiplier", "3"),
					resource.TestCheckResourceAttr("data.sdwan_system_bfd_profile_parcel.test", "colors.0.pmtu_discovery", "true"),
					resource.TestCheckResourceAttr("data.sdwan_system_bfd_profile_parcel.test", "colors.0.dscp", "16"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanSystemBFDProfileParcelConfig = `
resource "sdwan_system_feature_profile" "test" {
  name = "TF_TEST"
  description = "Terraform test"
}

resource "sdwan_system_bfd_profile_parcel" "test" {
  name = "TF_TEST"
  description = "Terraform integration test"
  feature_profile_id = sdwan_system_feature_profile.test.id
  multiplier = 3
  poll_interval = 100
  default_dscp = 8
  colors = [{
    color = "3g"
    hello_interval = 200
    multiplier = 3
    pmtu_discovery = true
    dscp = 16
  }]
}

data "sdwan_system_bfd_profile_parcel" "test" {
  id = sdwan_system_bfd_profile_parcel.test.id
  feature_profile_id = sdwan_system_feature_profile.test.id
}
`
