// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/CiscoDevNet/terraform-provider-sdwan/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type DNSSecurityPolicyDefinition struct {
	Id                                        types.String `tfsdk:"id"`
	Version                                   types.Int64  `tfsdk:"version"`
	Name                                      types.String `tfsdk:"name"`
	Description                               types.String `tfsdk:"description"`
	DomainListId                              types.String `tfsdk:"domain_list_id"`
	DomainListVersion                         types.Int64  `tfsdk:"domain_list_version"`
	LocalDomainBypassEnabled                  types.Bool   `tfsdk:"local_domain_bypass_enabled"`
	MatchAllVpn                               types.Bool   `tfsdk:"match_all_vpn"`
	TargetVpns                                types.List   `tfsdk:"target_vpns"`
	Dnscrypt                                  types.Bool   `tfsdk:"dnscrypt"`
	UmbrellaDnsDefault                        types.Bool   `tfsdk:"umbrella_dns_default"`
	CustomDnsServerIp                         types.String `tfsdk:"custom_dns_server_ip"`
	CiscoSigCredentialsFeatureTemplateId      types.String `tfsdk:"cisco_sig_credentials_feature_template_id"`
	CiscoSigCredentialsFeatureTemplateVersion types.Int64  `tfsdk:"cisco_sig_credentials_feature_template_version"`
}

func (data DNSSecurityPolicyDefinition) toBody(ctx context.Context) string {
	body := ""
	if true {
		body, _ = sjson.Set(body, "type", "DNSSecurity")
	}
	if !data.Name.IsNull() {
		body, _ = sjson.Set(body, "name", data.Name.ValueString())
	}
	if !data.Description.IsNull() {
		body, _ = sjson.Set(body, "description", data.Description.ValueString())
	}
	if !data.DomainListId.IsNull() {
		body, _ = sjson.Set(body, "definition.localDomainBypassList.ref", data.DomainListId.ValueString())
	}
	if !data.LocalDomainBypassEnabled.IsNull() {
		if false && data.LocalDomainBypassEnabled.ValueBool() {
			body, _ = sjson.Set(body, "definition.localDomainBypassEnabled", "")
		} else {
			body, _ = sjson.Set(body, "definition.localDomainBypassEnabled", data.LocalDomainBypassEnabled.ValueBool())
		}
	}
	if !data.MatchAllVpn.IsNull() {
		if false && data.MatchAllVpn.ValueBool() {
			body, _ = sjson.Set(body, "definition.matchAllVpn", "")
		} else {
			body, _ = sjson.Set(body, "definition.matchAllVpn", data.MatchAllVpn.ValueBool())
		}
	}
	if !data.TargetVpns.IsNull() {
		var values []string
		data.TargetVpns.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "definition.targetVpns", values)
	}
	if !data.Dnscrypt.IsNull() {
		if false && data.Dnscrypt.ValueBool() {
			body, _ = sjson.Set(body, "definition.dnsCrypt", "")
		} else {
			body, _ = sjson.Set(body, "definition.dnsCrypt", data.Dnscrypt.ValueBool())
		}
	}
	if !data.UmbrellaDnsDefault.IsNull() {
		if false && data.UmbrellaDnsDefault.ValueBool() {
			body, _ = sjson.Set(body, "definition.umbrellaDefault", "")
		} else {
			body, _ = sjson.Set(body, "definition.umbrellaDefault", data.UmbrellaDnsDefault.ValueBool())
		}
	}
	if !data.CustomDnsServerIp.IsNull() {
		body, _ = sjson.Set(body, "definition.dnsServerIP", data.CustomDnsServerIp.ValueString())
	}
	if !data.CiscoSigCredentialsFeatureTemplateId.IsNull() {
		body, _ = sjson.Set(body, "definition.umbrellaData.ref", data.CiscoSigCredentialsFeatureTemplateId.ValueString())
	}
	return body
}

func (data *DNSSecurityPolicyDefinition) fromBody(ctx context.Context, res gjson.Result) {
	state := *data
	if value := res.Get("name"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("definition.localDomainBypassList.ref"); value.Exists() {
		data.DomainListId = types.StringValue(value.String())
	} else {
		data.DomainListId = types.StringNull()
	}
	if value := res.Get("definition.localDomainBypassEnabled"); value.Exists() {
		if false && value.String() == "" {
			data.LocalDomainBypassEnabled = types.BoolValue(true)
		} else {
			data.LocalDomainBypassEnabled = types.BoolValue(value.Bool())
		}
	} else {
		data.LocalDomainBypassEnabled = types.BoolNull()
	}
	if value := res.Get("definition.matchAllVpn"); value.Exists() {
		if false && value.String() == "" {
			data.MatchAllVpn = types.BoolValue(true)
		} else {
			data.MatchAllVpn = types.BoolValue(value.Bool())
		}
	} else {
		data.MatchAllVpn = types.BoolNull()
	}
	if value := res.Get("definition.targetVpns"); value.Exists() {
		data.TargetVpns = helpers.GetStringList(value.Array())
	} else {
		data.TargetVpns = types.ListNull(types.StringType)
	}
	if value := res.Get("definition.dnsCrypt"); value.Exists() {
		if false && value.String() == "" {
			data.Dnscrypt = types.BoolValue(true)
		} else {
			data.Dnscrypt = types.BoolValue(value.Bool())
		}
	} else {
		data.Dnscrypt = types.BoolNull()
	}
	if value := res.Get("definition.umbrellaDefault"); value.Exists() {
		if false && value.String() == "" {
			data.UmbrellaDnsDefault = types.BoolValue(true)
		} else {
			data.UmbrellaDnsDefault = types.BoolValue(value.Bool())
		}
	} else {
		data.UmbrellaDnsDefault = types.BoolNull()
	}
	if value := res.Get("definition.dnsServerIP"); value.Exists() {
		data.CustomDnsServerIp = types.StringValue(value.String())
	} else {
		data.CustomDnsServerIp = types.StringNull()
	}
	if value := res.Get("definition.umbrellaData.ref"); value.Exists() {
		data.CiscoSigCredentialsFeatureTemplateId = types.StringValue(value.String())
	} else {
		data.CiscoSigCredentialsFeatureTemplateId = types.StringNull()
	}
	data.updateVersions(ctx, &state)
}

func (data *DNSSecurityPolicyDefinition) hasChanges(ctx context.Context, state *DNSSecurityPolicyDefinition) bool {
	hasChanges := false
	if !data.Name.Equal(state.Name) {
		hasChanges = true
	}
	if !data.Description.Equal(state.Description) {
		hasChanges = true
	}
	if !data.DomainListId.Equal(state.DomainListId) {
		hasChanges = true
	}
	if !data.LocalDomainBypassEnabled.Equal(state.LocalDomainBypassEnabled) {
		hasChanges = true
	}
	if !data.MatchAllVpn.Equal(state.MatchAllVpn) {
		hasChanges = true
	}
	if !data.TargetVpns.Equal(state.TargetVpns) {
		hasChanges = true
	}
	if !data.Dnscrypt.Equal(state.Dnscrypt) {
		hasChanges = true
	}
	if !data.UmbrellaDnsDefault.Equal(state.UmbrellaDnsDefault) {
		hasChanges = true
	}
	if !data.CustomDnsServerIp.Equal(state.CustomDnsServerIp) {
		hasChanges = true
	}
	if !data.CiscoSigCredentialsFeatureTemplateId.Equal(state.CiscoSigCredentialsFeatureTemplateId) {
		hasChanges = true
	}
	return hasChanges
}

func (data *DNSSecurityPolicyDefinition) updateVersions(ctx context.Context, state *DNSSecurityPolicyDefinition) {
	data.DomainListVersion = state.DomainListVersion
	data.CiscoSigCredentialsFeatureTemplateVersion = state.CiscoSigCredentialsFeatureTemplateVersion
}
