// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type CustomControlTopology struct {
	Id            types.String                     `tfsdk:"id"`
	Version       types.Int64                      `tfsdk:"version"`
	Type          types.String                     `tfsdk:"type"`
	Name          types.String                     `tfsdk:"name"`
	Description   types.String                     `tfsdk:"description"`
	DefaultAction types.String                     `tfsdk:"default_action"`
	Sequences     []CustomControlTopologySequences `tfsdk:"sequences"`
}

type CustomControlTopologySequences struct {
	Id            types.Int64                                   `tfsdk:"id"`
	Name          types.String                                  `tfsdk:"name"`
	Type          types.String                                  `tfsdk:"type"`
	IpType        types.String                                  `tfsdk:"ip_type"`
	MatchEntries  []CustomControlTopologySequencesMatchEntries  `tfsdk:"match_entries"`
	ActionEntries []CustomControlTopologySequencesActionEntries `tfsdk:"action_entries"`
}

type CustomControlTopologySequencesMatchEntries struct {
	Type                         types.String `tfsdk:"type"`
	ColorListId                  types.String `tfsdk:"color_list_id"`
	ColorListVersion             types.Int64  `tfsdk:"color_list_version"`
	CommunityListId              types.String `tfsdk:"community_list_id"`
	CommunityListVersion         types.Int64  `tfsdk:"community_list_version"`
	ExpandedCommunityListId      types.String `tfsdk:"expanded_community_list_id"`
	ExpandedCommunityListVersion types.Int64  `tfsdk:"expanded_community_list_version"`
	OmpTag                       types.Int64  `tfsdk:"omp_tag"`
	Origin                       types.String `tfsdk:"origin"`
	Originator                   types.String `tfsdk:"originator"`
	Preference                   types.Int64  `tfsdk:"preference"`
	SiteListId                   types.String `tfsdk:"site_list_id"`
	SiteListVersion              types.Int64  `tfsdk:"site_list_version"`
	PathType                     types.String `tfsdk:"path_type"`
	TlocListId                   types.String `tfsdk:"tloc_list_id"`
	TlocListVersion              types.Int64  `tfsdk:"tloc_list_version"`
	VpnListId                    types.String `tfsdk:"vpn_list_id"`
	VpnListVersion               types.Int64  `tfsdk:"vpn_list_version"`
	PrefixListId                 types.String `tfsdk:"prefix_list_id"`
	PrefixListVersion            types.Int64  `tfsdk:"prefix_list_version"`
	VpnId                        types.Int64  `tfsdk:"vpn_id"`
	TlocIp                       types.String `tfsdk:"tloc_ip"`
	TlocColor                    types.String `tfsdk:"tloc_color"`
	TlocEncapsulation            types.String `tfsdk:"tloc_encapsulation"`
	SiteId                       types.Int64  `tfsdk:"site_id"`
	Carrier                      types.String `tfsdk:"carrier"`
	DomainId                     types.Int64  `tfsdk:"domain_id"`
	GroupId                      types.Int64  `tfsdk:"group_id"`
}
type CustomControlTopologySequencesActionEntries struct {
	Type                   types.String                                               `tfsdk:"type"`
	SetParameters          []CustomControlTopologySequencesActionEntriesSetParameters `tfsdk:"set_parameters"`
	ExportToVpnListId      types.String                                               `tfsdk:"export_to_vpn_list_id"`
	ExportToVpnListVersion types.Int64                                                `tfsdk:"export_to_vpn_list_version"`
}

type CustomControlTopologySequencesActionEntriesSetParameters struct {
	Type                     types.String `tfsdk:"type"`
	TlocListId               types.String `tfsdk:"tloc_list_id"`
	TlocListVersion          types.Int64  `tfsdk:"tloc_list_version"`
	TlocIp                   types.String `tfsdk:"tloc_ip"`
	TlocColor                types.String `tfsdk:"tloc_color"`
	TlocEncapsulation        types.String `tfsdk:"tloc_encapsulation"`
	TlocAction               types.String `tfsdk:"tloc_action"`
	Preference               types.Int64  `tfsdk:"preference"`
	OmpTag                   types.Int64  `tfsdk:"omp_tag"`
	Community                types.String `tfsdk:"community"`
	CommunityAdditive        types.Bool   `tfsdk:"community_additive"`
	ServiceType              types.String `tfsdk:"service_type"`
	ServiceVpnId             types.Int64  `tfsdk:"service_vpn_id"`
	ServiceTlocListId        types.String `tfsdk:"service_tloc_list_id"`
	ServiceTlocListVersion   types.Int64  `tfsdk:"service_tloc_list_version"`
	ServiceTlocIp            types.String `tfsdk:"service_tloc_ip"`
	ServiceTlocColor         types.String `tfsdk:"service_tloc_color"`
	ServiceTlocEncapsulation types.String `tfsdk:"service_tloc_encapsulation"`
}

func (data CustomControlTopology) getType() string {
	return "control"
}

func (data CustomControlTopology) toBody(ctx context.Context) string {
	body, _ := sjson.Set("", "name", data.Name.ValueString())
	body, _ = sjson.Set(body, "description", data.Description.ValueString())
	body, _ = sjson.Set(body, "type", "control")
	path := ""
	if !data.DefaultAction.IsNull() {
		body, _ = sjson.Set(body, path+"defaultAction.type", data.DefaultAction.ValueString())
	}
	if len(data.Sequences) > 0 {
		body, _ = sjson.Set(body, path+"sequences", []interface{}{})
		for _, item := range data.Sequences {
			itemBody := ""
			if !item.Id.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "sequenceId", item.Id.ValueInt64())
			}
			if !item.Name.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "sequenceName", item.Name.ValueString())
			}
			if !item.Type.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "sequenceType", item.Type.ValueString())
			}
			if !item.IpType.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "sequenceIpType", item.IpType.ValueString())
			}
			if len(item.MatchEntries) > 0 {
				itemBody, _ = sjson.Set(itemBody, "match.entries", []interface{}{})
				for _, childItem := range item.MatchEntries {
					itemChildBody := ""
					if !childItem.Type.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "field", childItem.Type.ValueString())
					}
					if !childItem.ColorListId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "ref", childItem.ColorListId.ValueString())
					}
					if !childItem.CommunityListId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "ref", childItem.CommunityListId.ValueString())
					}
					if !childItem.ExpandedCommunityListId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "ref", childItem.ExpandedCommunityListId.ValueString())
					}
					if !childItem.OmpTag.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value", fmt.Sprint(childItem.OmpTag.ValueInt64()))
					}
					if !childItem.Origin.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value", childItem.Origin.ValueString())
					}
					if !childItem.Originator.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value", childItem.Originator.ValueString())
					}
					if !childItem.Preference.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value", fmt.Sprint(childItem.Preference.ValueInt64()))
					}
					if !childItem.SiteListId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "ref", childItem.SiteListId.ValueString())
					}
					if !childItem.PathType.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value", childItem.PathType.ValueString())
					}
					if !childItem.TlocListId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "ref", childItem.TlocListId.ValueString())
					}
					if !childItem.VpnListId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "ref", childItem.VpnListId.ValueString())
					}
					if !childItem.PrefixListId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "ref", childItem.PrefixListId.ValueString())
					}
					if !childItem.VpnId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value", fmt.Sprint(childItem.VpnId.ValueInt64()))
					}
					if !childItem.TlocIp.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value.ip", childItem.TlocIp.ValueString())
					}
					if !childItem.TlocColor.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value.color", childItem.TlocColor.ValueString())
					}
					if !childItem.TlocEncapsulation.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value.encap", childItem.TlocEncapsulation.ValueString())
					}
					if !childItem.SiteId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value", fmt.Sprint(childItem.SiteId.ValueInt64()))
					}
					if !childItem.Carrier.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value", childItem.Carrier.ValueString())
					}
					if !childItem.DomainId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value", fmt.Sprint(childItem.DomainId.ValueInt64()))
					}
					if !childItem.GroupId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "value", fmt.Sprint(childItem.GroupId.ValueInt64()))
					}
					itemBody, _ = sjson.SetRaw(itemBody, "match.entries.-1", itemChildBody)
				}
			}
			if len(item.ActionEntries) > 0 {
				itemBody, _ = sjson.Set(itemBody, "actions", []interface{}{})
				for _, childItem := range item.ActionEntries {
					itemChildBody := ""
					if !childItem.Type.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "type", childItem.Type.ValueString())
					}
					if len(childItem.SetParameters) > 0 {
						itemChildBody, _ = sjson.Set(itemChildBody, "parameter", []interface{}{})
						for _, childChildItem := range childItem.SetParameters {
							itemChildChildBody := ""
							if !childChildItem.Type.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "field", childChildItem.Type.ValueString())
							}
							if !childChildItem.TlocListId.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "ref", childChildItem.TlocListId.ValueString())
							}
							if !childChildItem.TlocIp.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value.ip", childChildItem.TlocIp.ValueString())
							}
							if !childChildItem.TlocColor.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value.color", childChildItem.TlocColor.ValueString())
							}
							if !childChildItem.TlocEncapsulation.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value.encap", childChildItem.TlocEncapsulation.ValueString())
							}
							if !childChildItem.TlocAction.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value", childChildItem.TlocAction.ValueString())
							}
							if !childChildItem.Preference.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value", fmt.Sprint(childChildItem.Preference.ValueInt64()))
							}
							if !childChildItem.OmpTag.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value", fmt.Sprint(childChildItem.OmpTag.ValueInt64()))
							}
							if !childChildItem.Community.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value", childChildItem.Community.ValueString())
							}
							if !childChildItem.ServiceType.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value.type", childChildItem.ServiceType.ValueString())
							}
							if !childChildItem.ServiceVpnId.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value.vpn", fmt.Sprint(childChildItem.ServiceVpnId.ValueInt64()))
							}
							if !childChildItem.ServiceTlocListId.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value.tlocList", childChildItem.ServiceTlocListId.ValueString())
							}
							if !childChildItem.ServiceTlocIp.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value.tloc.ip", childChildItem.ServiceTlocIp.ValueString())
							}
							if !childChildItem.ServiceTlocColor.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value.tloc.color", childChildItem.ServiceTlocColor.ValueString())
							}
							if !childChildItem.ServiceTlocEncapsulation.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "value.tloc.encap", childChildItem.ServiceTlocEncapsulation.ValueString())
							}
							itemChildBody, _ = sjson.SetRaw(itemChildBody, "parameter.-1", itemChildChildBody)
						}
					}
					if !childItem.ExportToVpnListId.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "parameter.ref", childItem.ExportToVpnListId.ValueString())
					}
					itemBody, _ = sjson.SetRaw(itemBody, "actions.-1", itemChildBody)
				}
			}
			body, _ = sjson.SetRaw(body, path+"sequences.-1", itemBody)
		}
	}
	return body
}

func (data *CustomControlTopology) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("name"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("type"); value.Exists() {
		data.Type = types.StringValue(value.String())
	} else {
		data.Type = types.StringNull()
	}
	path := ""
	if value := res.Get(path + "defaultAction.type"); value.Exists() {
		data.DefaultAction = types.StringValue(value.String())
	} else {
		data.DefaultAction = types.StringNull()
	}
	if value := res.Get(path + "sequences"); value.Exists() {
		data.Sequences = make([]CustomControlTopologySequences, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := CustomControlTopologySequences{}
			if cValue := v.Get("sequenceId"); cValue.Exists() {
				item.Id = types.Int64Value(cValue.Int())
			} else {
				item.Id = types.Int64Null()
			}
			if cValue := v.Get("sequenceName"); cValue.Exists() {
				item.Name = types.StringValue(cValue.String())
			} else {
				item.Name = types.StringNull()
			}
			if cValue := v.Get("sequenceType"); cValue.Exists() {
				item.Type = types.StringValue(cValue.String())
			} else {
				item.Type = types.StringNull()
			}
			if cValue := v.Get("sequenceIpType"); cValue.Exists() {
				item.IpType = types.StringValue(cValue.String())
			} else {
				item.IpType = types.StringNull()
			}
			if cValue := v.Get("match.entries"); cValue.Exists() {
				item.MatchEntries = make([]CustomControlTopologySequencesMatchEntries, 0)
				cValue.ForEach(func(ck, cv gjson.Result) bool {
					cItem := CustomControlTopologySequencesMatchEntries{}
					if ccValue := cv.Get("field"); ccValue.Exists() {
						cItem.Type = types.StringValue(ccValue.String())
					} else {
						cItem.Type = types.StringNull()
					}
					if ccValue := cv.Get("ref"); cItem.Type.ValueString() == "colorList" && ccValue.Exists() {
						cItem.ColorListId = types.StringValue(ccValue.String())
					} else {
						cItem.ColorListId = types.StringNull()
					}
					if ccValue := cv.Get("ref"); cItem.Type.ValueString() == "community" && ccValue.Exists() {
						cItem.CommunityListId = types.StringValue(ccValue.String())
					} else {
						cItem.CommunityListId = types.StringNull()
					}
					if ccValue := cv.Get("ref"); cItem.Type.ValueString() == "expandedCommunity" && ccValue.Exists() {
						cItem.ExpandedCommunityListId = types.StringValue(ccValue.String())
					} else {
						cItem.ExpandedCommunityListId = types.StringNull()
					}
					if ccValue := cv.Get("value"); cItem.Type.ValueString() == "ompTag" && ccValue.Exists() {
						cItem.OmpTag = types.Int64Value(ccValue.Int())
					} else {
						cItem.OmpTag = types.Int64Null()
					}
					if ccValue := cv.Get("value"); cItem.Type.ValueString() == "origin" && ccValue.Exists() {
						cItem.Origin = types.StringValue(ccValue.String())
					} else {
						cItem.Origin = types.StringNull()
					}
					if ccValue := cv.Get("value"); cItem.Type.ValueString() == "originator" && ccValue.Exists() {
						cItem.Originator = types.StringValue(ccValue.String())
					} else {
						cItem.Originator = types.StringNull()
					}
					if ccValue := cv.Get("value"); cItem.Type.ValueString() == "preference" && ccValue.Exists() {
						cItem.Preference = types.Int64Value(ccValue.Int())
					} else {
						cItem.Preference = types.Int64Null()
					}
					if ccValue := cv.Get("ref"); cItem.Type.ValueString() == "siteList" && ccValue.Exists() {
						cItem.SiteListId = types.StringValue(ccValue.String())
					} else {
						cItem.SiteListId = types.StringNull()
					}
					if ccValue := cv.Get("value"); cItem.Type.ValueString() == "pathType" && ccValue.Exists() {
						cItem.PathType = types.StringValue(ccValue.String())
					} else {
						cItem.PathType = types.StringNull()
					}
					if ccValue := cv.Get("ref"); cItem.Type.ValueString() == "tlocList" && ccValue.Exists() {
						cItem.TlocListId = types.StringValue(ccValue.String())
					} else {
						cItem.TlocListId = types.StringNull()
					}
					if ccValue := cv.Get("ref"); cItem.Type.ValueString() == "vpnList" && ccValue.Exists() {
						cItem.VpnListId = types.StringValue(ccValue.String())
					} else {
						cItem.VpnListId = types.StringNull()
					}
					if ccValue := cv.Get("ref"); cItem.Type.ValueString() == "prefixList" && ccValue.Exists() {
						cItem.PrefixListId = types.StringValue(ccValue.String())
					} else {
						cItem.PrefixListId = types.StringNull()
					}
					if ccValue := cv.Get("value"); cItem.Type.ValueString() == "vpn" && ccValue.Exists() {
						cItem.VpnId = types.Int64Value(ccValue.Int())
					} else {
						cItem.VpnId = types.Int64Null()
					}
					if ccValue := cv.Get("value.ip"); cItem.Type.ValueString() == "tloc" && ccValue.Exists() {
						cItem.TlocIp = types.StringValue(ccValue.String())
					} else {
						cItem.TlocIp = types.StringNull()
					}
					if ccValue := cv.Get("value.color"); cItem.Type.ValueString() == "tloc" && ccValue.Exists() {
						cItem.TlocColor = types.StringValue(ccValue.String())
					} else {
						cItem.TlocColor = types.StringNull()
					}
					if ccValue := cv.Get("value.encap"); cItem.Type.ValueString() == "tloc" && ccValue.Exists() {
						cItem.TlocEncapsulation = types.StringValue(ccValue.String())
					} else {
						cItem.TlocEncapsulation = types.StringNull()
					}
					if ccValue := cv.Get("value"); cItem.Type.ValueString() == "siteId" && ccValue.Exists() {
						cItem.SiteId = types.Int64Value(ccValue.Int())
					} else {
						cItem.SiteId = types.Int64Null()
					}
					if ccValue := cv.Get("value"); cItem.Type.ValueString() == "carrier" && ccValue.Exists() {
						cItem.Carrier = types.StringValue(ccValue.String())
					} else {
						cItem.Carrier = types.StringNull()
					}
					if ccValue := cv.Get("value"); cItem.Type.ValueString() == "domainId" && ccValue.Exists() {
						cItem.DomainId = types.Int64Value(ccValue.Int())
					} else {
						cItem.DomainId = types.Int64Null()
					}
					if ccValue := cv.Get("value"); cItem.Type.ValueString() == "groupId" && ccValue.Exists() {
						cItem.GroupId = types.Int64Value(ccValue.Int())
					} else {
						cItem.GroupId = types.Int64Null()
					}
					item.MatchEntries = append(item.MatchEntries, cItem)
					return true
				})
			}
			if cValue := v.Get("actions"); cValue.Exists() {
				item.ActionEntries = make([]CustomControlTopologySequencesActionEntries, 0)
				cValue.ForEach(func(ck, cv gjson.Result) bool {
					cItem := CustomControlTopologySequencesActionEntries{}
					if ccValue := cv.Get("type"); ccValue.Exists() {
						cItem.Type = types.StringValue(ccValue.String())
					} else {
						cItem.Type = types.StringNull()
					}
					if ccValue := cv.Get("parameter"); ccValue.Exists() {
						cItem.SetParameters = make([]CustomControlTopologySequencesActionEntriesSetParameters, 0)
						ccValue.ForEach(func(cck, ccv gjson.Result) bool {
							ccItem := CustomControlTopologySequencesActionEntriesSetParameters{}
							if cccValue := ccv.Get("field"); cccValue.Exists() {
								ccItem.Type = types.StringValue(cccValue.String())
							} else {
								ccItem.Type = types.StringNull()
							}
							if cccValue := ccv.Get("ref"); ccItem.Type.ValueString() == "tlocList" && cccValue.Exists() {
								ccItem.TlocListId = types.StringValue(cccValue.String())
							} else {
								ccItem.TlocListId = types.StringNull()
							}
							if cccValue := ccv.Get("value.ip"); ccItem.Type.ValueString() == "tloc" && cccValue.Exists() {
								ccItem.TlocIp = types.StringValue(cccValue.String())
							} else {
								ccItem.TlocIp = types.StringNull()
							}
							if cccValue := ccv.Get("value.color"); ccItem.Type.ValueString() == "tloc" && cccValue.Exists() {
								ccItem.TlocColor = types.StringValue(cccValue.String())
							} else {
								ccItem.TlocColor = types.StringNull()
							}
							if cccValue := ccv.Get("value.encap"); ccItem.Type.ValueString() == "tloc" && cccValue.Exists() {
								ccItem.TlocEncapsulation = types.StringValue(cccValue.String())
							} else {
								ccItem.TlocEncapsulation = types.StringNull()
							}
							if cccValue := ccv.Get("value"); ccItem.Type.ValueString() == "tlocAction" && cccValue.Exists() {
								ccItem.TlocAction = types.StringValue(cccValue.String())
							} else {
								ccItem.TlocAction = types.StringNull()
							}
							if cccValue := ccv.Get("value"); ccItem.Type.ValueString() == "preference" && cccValue.Exists() {
								ccItem.Preference = types.Int64Value(cccValue.Int())
							} else {
								ccItem.Preference = types.Int64Null()
							}
							if cccValue := ccv.Get("value"); ccItem.Type.ValueString() == "ompTag" && cccValue.Exists() {
								ccItem.OmpTag = types.Int64Value(cccValue.Int())
							} else {
								ccItem.OmpTag = types.Int64Null()
							}
							if cccValue := ccv.Get("value"); ccItem.Type.ValueString() == "community" && cccValue.Exists() {
								ccItem.Community = types.StringValue(cccValue.String())
							} else {
								ccItem.Community = types.StringNull()
							}
							if cccValue := ccv.Get("value.type"); ccItem.Type.ValueString() == "service" && cccValue.Exists() {
								ccItem.ServiceType = types.StringValue(cccValue.String())
							} else {
								ccItem.ServiceType = types.StringNull()
							}
							if cccValue := ccv.Get("value.vpn"); ccItem.Type.ValueString() == "service" && cccValue.Exists() {
								ccItem.ServiceVpnId = types.Int64Value(cccValue.Int())
							} else {
								ccItem.ServiceVpnId = types.Int64Null()
							}
							if cccValue := ccv.Get("value.tlocList"); ccItem.Type.ValueString() == "service" && cccValue.Exists() {
								ccItem.ServiceTlocListId = types.StringValue(cccValue.String())
							} else {
								ccItem.ServiceTlocListId = types.StringNull()
							}
							if cccValue := ccv.Get("value.tloc.ip"); ccItem.Type.ValueString() == "service" && cccValue.Exists() {
								ccItem.ServiceTlocIp = types.StringValue(cccValue.String())
							} else {
								ccItem.ServiceTlocIp = types.StringNull()
							}
							if cccValue := ccv.Get("value.tloc.color"); ccItem.Type.ValueString() == "service" && cccValue.Exists() {
								ccItem.ServiceTlocColor = types.StringValue(cccValue.String())
							} else {
								ccItem.ServiceTlocColor = types.StringNull()
							}
							if cccValue := ccv.Get("value.tloc.encap"); ccItem.Type.ValueString() == "service" && cccValue.Exists() {
								ccItem.ServiceTlocEncapsulation = types.StringValue(cccValue.String())
							} else {
								ccItem.ServiceTlocEncapsulation = types.StringNull()
							}
							cItem.SetParameters = append(cItem.SetParameters, ccItem)
							return true
						})
					}
					if ccValue := cv.Get("parameter.ref"); ccValue.Exists() {
						cItem.ExportToVpnListId = types.StringValue(ccValue.String())
					} else {
						cItem.ExportToVpnListId = types.StringNull()
					}
					item.ActionEntries = append(item.ActionEntries, cItem)
					return true
				})
			}
			data.Sequences = append(data.Sequences, item)
			return true
		})
	}
}

func (data *CustomControlTopology) hasChanges(ctx context.Context, state *CustomControlTopology) bool {
	hasChanges := false
	if !data.Name.Equal(state.Name) {
		hasChanges = true
	}
	if !data.Description.Equal(state.Description) {
		hasChanges = true
	}
	if !data.DefaultAction.Equal(state.DefaultAction) {
		hasChanges = true
	}
	if len(data.Sequences) != len(state.Sequences) {
		hasChanges = true
	} else {
		for i := range data.Sequences {
			if !data.Sequences[i].Id.Equal(state.Sequences[i].Id) {
				hasChanges = true
			}
			if !data.Sequences[i].Name.Equal(state.Sequences[i].Name) {
				hasChanges = true
			}
			if !data.Sequences[i].Type.Equal(state.Sequences[i].Type) {
				hasChanges = true
			}
			if !data.Sequences[i].IpType.Equal(state.Sequences[i].IpType) {
				hasChanges = true
			}
			if len(data.Sequences[i].MatchEntries) != len(state.Sequences[i].MatchEntries) {
				hasChanges = true
			} else {
				for ii := range data.Sequences[i].MatchEntries {
					if !data.Sequences[i].MatchEntries[ii].Type.Equal(state.Sequences[i].MatchEntries[ii].Type) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].ColorListId.Equal(state.Sequences[i].MatchEntries[ii].ColorListId) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].CommunityListId.Equal(state.Sequences[i].MatchEntries[ii].CommunityListId) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].ExpandedCommunityListId.Equal(state.Sequences[i].MatchEntries[ii].ExpandedCommunityListId) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].OmpTag.Equal(state.Sequences[i].MatchEntries[ii].OmpTag) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].Origin.Equal(state.Sequences[i].MatchEntries[ii].Origin) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].Originator.Equal(state.Sequences[i].MatchEntries[ii].Originator) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].Preference.Equal(state.Sequences[i].MatchEntries[ii].Preference) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].SiteListId.Equal(state.Sequences[i].MatchEntries[ii].SiteListId) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].PathType.Equal(state.Sequences[i].MatchEntries[ii].PathType) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].TlocListId.Equal(state.Sequences[i].MatchEntries[ii].TlocListId) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].VpnListId.Equal(state.Sequences[i].MatchEntries[ii].VpnListId) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].PrefixListId.Equal(state.Sequences[i].MatchEntries[ii].PrefixListId) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].VpnId.Equal(state.Sequences[i].MatchEntries[ii].VpnId) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].TlocIp.Equal(state.Sequences[i].MatchEntries[ii].TlocIp) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].TlocColor.Equal(state.Sequences[i].MatchEntries[ii].TlocColor) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].TlocEncapsulation.Equal(state.Sequences[i].MatchEntries[ii].TlocEncapsulation) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].SiteId.Equal(state.Sequences[i].MatchEntries[ii].SiteId) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].Carrier.Equal(state.Sequences[i].MatchEntries[ii].Carrier) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].DomainId.Equal(state.Sequences[i].MatchEntries[ii].DomainId) {
						hasChanges = true
					}
					if !data.Sequences[i].MatchEntries[ii].GroupId.Equal(state.Sequences[i].MatchEntries[ii].GroupId) {
						hasChanges = true
					}
				}
			}
			if len(data.Sequences[i].ActionEntries) != len(state.Sequences[i].ActionEntries) {
				hasChanges = true
			} else {
				for ii := range data.Sequences[i].ActionEntries {
					if !data.Sequences[i].ActionEntries[ii].Type.Equal(state.Sequences[i].ActionEntries[ii].Type) {
						hasChanges = true
					}
					if len(data.Sequences[i].ActionEntries[ii].SetParameters) != len(state.Sequences[i].ActionEntries[ii].SetParameters) {
						hasChanges = true
					} else {
						for iii := range data.Sequences[i].ActionEntries[ii].SetParameters {
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].Type.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].Type) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].TlocListId.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].TlocListId) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].TlocIp.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].TlocIp) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].TlocColor.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].TlocColor) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].TlocEncapsulation.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].TlocEncapsulation) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].TlocAction.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].TlocAction) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].Preference.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].Preference) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].OmpTag.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].OmpTag) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].Community.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].Community) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].CommunityAdditive.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].CommunityAdditive) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceType.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceType) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceVpnId.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceVpnId) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceTlocListId.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceTlocListId) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceTlocIp.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceTlocIp) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceTlocColor.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceTlocColor) {
								hasChanges = true
							}
							if !data.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceTlocEncapsulation.Equal(state.Sequences[i].ActionEntries[ii].SetParameters[iii].ServiceTlocEncapsulation) {
								hasChanges = true
							}
						}
					}
					if !data.Sequences[i].ActionEntries[ii].ExportToVpnListId.Equal(state.Sequences[i].ActionEntries[ii].ExportToVpnListId) {
						hasChanges = true
					}
				}
			}
		}
	}
	return hasChanges
}

func (data *CustomControlTopology) getMatchColorListVersion(ctx context.Context, name string, id int64) types.Int64 {
	for _, item := range data.Sequences {
		if item.Name.ValueString() == name && item.Id.ValueInt64() == id {
			for _, cItem := range item.MatchEntries {
				if cItem.Type.ValueString() == "colorList" {
					return cItem.ColorListVersion
				}
			}
		}
	}
	return types.Int64Null()
}

func (data *CustomControlTopology) getMatchCommunityListVersion(ctx context.Context, name string, id int64) types.Int64 {
	for _, item := range data.Sequences {
		if item.Name.ValueString() == name && item.Id.ValueInt64() == id {
			for _, cItem := range item.MatchEntries {
				if cItem.Type.ValueString() == "community" {
					return cItem.CommunityListVersion
				}
			}
		}
	}
	return types.Int64Null()
}

func (data *CustomControlTopology) getMatchExpandedCommunityListVersion(ctx context.Context, name string, id int64) types.Int64 {
	for _, item := range data.Sequences {
		if item.Name.ValueString() == name && item.Id.ValueInt64() == id {
			for _, cItem := range item.MatchEntries {
				if cItem.Type.ValueString() == "expandedCommunity" {
					return cItem.ExpandedCommunityListVersion
				}
			}
		}
	}
	return types.Int64Null()
}

func (data *CustomControlTopology) getMatchSiteListVersion(ctx context.Context, name string, id int64) types.Int64 {
	for _, item := range data.Sequences {
		if item.Name.ValueString() == name && item.Id.ValueInt64() == id {
			for _, cItem := range item.MatchEntries {
				if cItem.Type.ValueString() == "siteList" {
					return cItem.SiteListVersion
				}
			}
		}
	}
	return types.Int64Null()
}

func (data *CustomControlTopology) getMatchTlocListVersion(ctx context.Context, name string, id int64) types.Int64 {
	for _, item := range data.Sequences {
		if item.Name.ValueString() == name && item.Id.ValueInt64() == id {
			for _, cItem := range item.MatchEntries {
				if cItem.Type.ValueString() == "tlocList" {
					return cItem.TlocListVersion
				}
			}
		}
	}
	return types.Int64Null()
}

func (data *CustomControlTopology) getMatchVpnListVersion(ctx context.Context, name string, id int64) types.Int64 {
	for _, item := range data.Sequences {
		if item.Name.ValueString() == name && item.Id.ValueInt64() == id {
			for _, cItem := range item.MatchEntries {
				if cItem.Type.ValueString() == "vpnList" {
					return cItem.VpnListVersion
				}
			}
		}
	}
	return types.Int64Null()
}

func (data *CustomControlTopology) getMatchPrefixListVersion(ctx context.Context, name string, id int64) types.Int64 {
	for _, item := range data.Sequences {
		if item.Name.ValueString() == name && item.Id.ValueInt64() == id {
			for _, cItem := range item.MatchEntries {
				if cItem.Type.ValueString() == "prefixList" {
					return cItem.PrefixListVersion
				}
			}
		}
	}
	return types.Int64Null()
}

func (data *CustomControlTopology) getActionExportToVpnListVersion(ctx context.Context, name string, id int64) types.Int64 {
	for _, item := range data.Sequences {
		if item.Name.ValueString() == name && item.Id.ValueInt64() == id {
			for _, cItem := range item.ActionEntries {
				if cItem.Type.ValueString() == "exportTo" {
					return cItem.ExportToVpnListVersion
				}
			}
		}
	}
	return types.Int64Null()
}

func (data *CustomControlTopology) getActionTlocListVersion(ctx context.Context, name string, id int64) types.Int64 {
	for _, item := range data.Sequences {
		if item.Name.ValueString() == name && item.Id.ValueInt64() == id {
			for _, cItem := range item.ActionEntries {
				if cItem.Type.ValueString() == "set" {
					for _, ccItem := range cItem.SetParameters {
						if ccItem.Type.ValueString() == "tlocList" {
							return ccItem.TlocListVersion
						}
					}
				}
			}
		}
	}
	return types.Int64Null()
}

func (data *CustomControlTopology) getActionServiceTlocListVersion(ctx context.Context, name string, id int64) types.Int64 {
	for _, item := range data.Sequences {
		if item.Name.ValueString() == name && item.Id.ValueInt64() == id {
			for _, cItem := range item.ActionEntries {
				if cItem.Type.ValueString() == "set" {
					for _, ccItem := range cItem.SetParameters {
						if ccItem.Type.ValueString() == "service" {
							return ccItem.ServiceTlocListVersion
						}
					}
				}
			}
		}
	}
	return types.Int64Null()
}

func (data *CustomControlTopology) updateVersions(ctx context.Context, state CustomControlTopology) {
	for s := range data.Sequences {
		id := data.Sequences[s].Id.ValueInt64()
		name := data.Sequences[s].Name.ValueString()
		for m := range data.Sequences[s].MatchEntries {
			t := data.Sequences[s].MatchEntries[m].Type.ValueString()
			if t == "colorList" {
				data.Sequences[s].MatchEntries[m].ColorListVersion = state.getMatchColorListVersion(ctx, name, id)
			} else if t == "community" {
				data.Sequences[s].MatchEntries[m].CommunityListVersion = state.getMatchCommunityListVersion(ctx, name, id)
			} else if t == "expandedCommunity" {
				data.Sequences[s].MatchEntries[m].ExpandedCommunityListVersion = state.getMatchExpandedCommunityListVersion(ctx, name, id)
			} else if t == "siteList" {
				data.Sequences[s].MatchEntries[m].SiteListVersion = state.getMatchSiteListVersion(ctx, name, id)
			} else if t == "tlocList" {
				data.Sequences[s].MatchEntries[m].TlocListVersion = state.getMatchTlocListVersion(ctx, name, id)
			} else if t == "vpnList" {
				data.Sequences[s].MatchEntries[m].VpnListVersion = state.getMatchVpnListVersion(ctx, name, id)
			} else if t == "prefixList" {
				data.Sequences[s].MatchEntries[m].PrefixListVersion = state.getMatchPrefixListVersion(ctx, name, id)
			}
		}
		for a := range data.Sequences[s].ActionEntries {
			t := data.Sequences[s].ActionEntries[a].Type.ValueString()
			if t == "set" {
				for s := range data.Sequences[s].ActionEntries[a].SetParameters {
					st := data.Sequences[s].ActionEntries[a].SetParameters[s].Type.ValueString()
					if st == "tlocList" {
						data.Sequences[s].ActionEntries[a].SetParameters[s].TlocListVersion = state.getActionTlocListVersion(ctx, name, id)
					} else if st == "service" && data.Sequences[s].ActionEntries[a].SetParameters[s].ServiceTlocListId.ValueString() != "" {
						data.Sequences[s].ActionEntries[a].SetParameters[s].ServiceTlocListVersion = state.getActionServiceTlocListVersion(ctx, name, id)
					}
				}
			} else if t == "exportTo" {
				data.Sequences[s].ActionEntries[a].ExportToVpnListVersion = state.getActionExportToVpnListVersion(ctx, name, id)
			}
		}
	}
}
