// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanCEdgeMulticastFeatureTemplate(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanCEdgeMulticastFeatureTemplateConfig_minimum(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_cedge_multicast_feature_template.test", "spt_only", "true"),
					resource.TestCheckResourceAttr("sdwan_cedge_multicast_feature_template.test", "local_replicator", "true"),
				),
			},
			{
				Config: testAccSdwanCEdgeMulticastFeatureTemplateConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_cedge_multicast_feature_template.test", "spt_only", "true"),
					resource.TestCheckResourceAttr("sdwan_cedge_multicast_feature_template.test", "local_replicator", "true"),
					resource.TestCheckResourceAttr("sdwan_cedge_multicast_feature_template.test", "threshold", "200"),
				),
			},
		},
	})
}

func testAccSdwanCEdgeMulticastFeatureTemplateConfig_minimum() string {
	return `
	resource "sdwan_cedge_multicast_feature_template" "test" {
		name = "TF_TEST_MIN"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
		spt_only = true
		local_replicator = true
	}
	`
}

func testAccSdwanCEdgeMulticastFeatureTemplateConfig_all() string {
	return `
	resource "sdwan_cedge_multicast_feature_template" "test" {
		name = "TF_TEST_ALL"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
		spt_only = true
		local_replicator = true
		threshold = 200
	}
	`
}
