// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanPolicerPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanPolicerPolicyObjectConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_policer_policy_object.test", "entries.0.burst", "100000"),
					resource.TestCheckResourceAttr("sdwan_policer_policy_object.test", "entries.0.exceed_action", "remark"),
					resource.TestCheckResourceAttr("sdwan_policer_policy_object.test", "entries.0.rate", "100"),
				),
			},
		},
	})
}

func testAccSdwanPolicerPolicyObjectConfig_all() string {
	return `
	resource "sdwan_policer_policy_object" "test" {
		name = "TF_TEST_ALL"
		entries = [{
			burst = 100000
			exceed_action = "remark"
			rate = 100
		}]
	}
	`
}
