resource "sdwan_service_lan_vpn_interface_gre_feature" "example" {
  name                            = "Example"
  description                     = "My Example"
  feature_profile_id              = "f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac"
  service_lan_vpn_feature_id      = "140331f6-5418-4755-a059-13c77eb96037"
  interface_name                  = "gre1"
  interface_description           = "gre1"
  ipv4_address                    = "70.1.1.1"
  ipv4_subnet_mask                = "255.255.255.0"
  ipv6_address                    = "2001:0:0:1::0"
  shutdown                        = true
  tunnel_protection               = false
  tunnel_mode                     = "ipv4"
  tunnel_source_ipv4_address      = "78.1.1.1"
  tunnel_destination_ipv4_address = "79.1.1.1"
  ipv4_mtu                        = 1500
  ipv4_tcp_mss                    = 1460
  clear_dont_fragment             = false
  dpd_interval                    = 10
  dpd_retries                     = 3
  ike_version                     = 1
  ike_mode                        = "main"
  ike_rekey_interval              = 14400
  ike_ciphersuite                 = "aes256-cbc-sha1"
  ike_group                       = "16"
  pre_shared_secret               = "123"
  ike_local_id                    = "xxx"
  ike_remote_id                   = "xxx"
  ipsec_rekey_interval            = 3600
  ipsec_replay_window             = 512
  ipsec_ciphersuite               = "aes256-gcm"
  perfect_forward_secrecy         = "group-16"
  application_tunnel_type         = "none"
}
